<?php

namespace ContainerLRdeH8l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FM_ZRi8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FM.zRi8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FM.zRi8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'supplier' => ['privates', '.errored..service_locator.FM.zRi8.App\\Entity\\Supplier', NULL, 'Cannot autowire service ".service_locator.FM.zRi8": it needs an instance of "App\\Entity\\Supplier" but this type has been excluded in "config/services.yaml".'],
        ], [
            'supplier' => 'App\\Entity\\Supplier',
        ]);
    }
}
