<?php

namespace ContainerOxYKCqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KfWBhnDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KfWBhnD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KfWBhnD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'exception' => ['privates', '.errored.k2RK9t4', NULL, 'Cannot determine controller argument for "App\\Controller\\ErrorController::show()": the $exception argument is type-hinted with the non-existent class or interface: "App\\Controller\\NotFoundHttpExpection". Did you forget to add a use statement?'],
        ], [
            'exception' => '?',
        ]);
    }
}
