<?php

namespace ContainerOxYKCqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_K2RK9t4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.k2RK9t4' shared service.
     *
     * @return \App\Controller\NotFoundHttpExpection
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ErrorController::show()": the $exception argument is type-hinted with the non-existent class or interface: "App\\Controller\\NotFoundHttpExpection". Did you forget to add a use statement?');
    }
}
