<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLemHRcN\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLemHRcN/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerLemHRcN.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerLemHRcN\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerLemHRcN\App_KernelProdContainer([
    'container.build_hash' => 'LemHRcN',
    'container.build_id' => 'b062ce1d',
    'container.build_time' => 1733753838,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLemHRcN');
