<?php

namespace ContainerEOxESWp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_14c4F_IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.14c4F.i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.14c4F.i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\ErrorController::show' => ['privates', '.service_locator.4elymRc', 'get_ServiceLocator_4elymRcService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.c0qcjBY', 'get_ServiceLocator_C0qcjBYService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SupplierController::delete' => ['privates', '.service_locator.dvS6U1.', 'get_ServiceLocator_DvS6U1_Service', true],
            'App\\Controller\\SupplierController::edit' => ['privates', '.service_locator.dvS6U1.', 'get_ServiceLocator_DvS6U1_Service', true],
            'App\\Controller\\SupplierController::index' => ['privates', '.service_locator.Vzzoljw', 'get_ServiceLocator_VzzoljwService', true],
            'App\\Controller\\SupplierController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SupplierController::show' => ['privates', '.service_locator.FM.zRi8', 'get_ServiceLocator_FM_ZRi8Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\ErrorController:show' => ['privates', '.service_locator.4elymRc', 'get_ServiceLocator_4elymRcService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.c0qcjBY', 'get_ServiceLocator_C0qcjBYService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SupplierController:delete' => ['privates', '.service_locator.dvS6U1.', 'get_ServiceLocator_DvS6U1_Service', true],
            'App\\Controller\\SupplierController:edit' => ['privates', '.service_locator.dvS6U1.', 'get_ServiceLocator_DvS6U1_Service', true],
            'App\\Controller\\SupplierController:index' => ['privates', '.service_locator.Vzzoljw', 'get_ServiceLocator_VzzoljwService', true],
            'App\\Controller\\SupplierController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SupplierController:show' => ['privates', '.service_locator.FM.zRi8', 'get_ServiceLocator_FM_ZRi8Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\ErrorController::show' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SupplierController::delete' => '?',
            'App\\Controller\\SupplierController::edit' => '?',
            'App\\Controller\\SupplierController::index' => '?',
            'App\\Controller\\SupplierController::new' => '?',
            'App\\Controller\\SupplierController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\ErrorController:show' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SupplierController:delete' => '?',
            'App\\Controller\\SupplierController:edit' => '?',
            'App\\Controller\\SupplierController:index' => '?',
            'App\\Controller\\SupplierController:new' => '?',
            'App\\Controller\\SupplierController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
