<?php

namespace ContainerDfca8mu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C0qcjBYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c0qcjBY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c0qcjBY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contactFormLimiter' => ['privates', 'limiter.contact_form', 'getLimiter_ContactFormService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'contactFormLimiter' => '?',
            'mailer' => '?',
        ]);
    }
}
