security:
    # Registrazione degli hash delle password
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Provider degli utenti
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        

    # Firewall
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\CustomAuthAuthenticator

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: /supplier
                enable_csrf: true

            logout:
                path: app_logout
                target: app_login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            entry_point: form_login
                # Uncomment to always enable "remember me"
                # always_remember_me: true

    # Controllo degli accessi
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/supplier, roles: ROLE_ADMIN }
        - { path: ^/tag, roles: ROLE_ADMIN }
       # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

# Configurazioni specifiche per l'ambiente di test
when@test:
    security:
        password_hashers:
            # Riduzione delle risorse per i test
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valore minimo per bcrypt
                time_cost: 3 # Valore minimo per argon
                memory_cost: 10 # Valore minimo per argon
