controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

_errors:
    resource: ../src/Controller/ErrorController.php
    type: annotation

admin_page:
    path: /admin
    controller: App\Controller\AdminController::index
