<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRjcycLb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRjcycLb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRjcycLb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRjcycLb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRjcycLb\App_KernelDevDebugContainer([
    'container.build_hash' => 'RjcycLb',
    'container.build_id' => '31ee7476',
    'container.build_time' => 1733835980,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRjcycLb');
