<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQTwoVeS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQTwoVeS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQTwoVeS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQTwoVeS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQTwoVeS\App_KernelDevDebugContainer([
    'container.build_hash' => 'QTwoVeS',
    'container.build_id' => '9c60145e',
    'container.build_time' => 1733930382,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQTwoVeS');
